export const colors = {
  cream: '#FFF8F0',
  lavender: '#6B5CE7',
  lavenderLight: '#8B7FED',
  blue: '#4A90D9',
  warmGray: '#6B7280',
  warmGrayLight: '#9CA3AF',
  white: '#FFFFFF',
  black: '#1F2937',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  calm: '#60A5FA',
  happy: '#34D399',
  sad: '#818CF8',
  anxious: '#FBBF24',
  confused: '#F97316',
  neutral: '#9CA3AF',
};

export const emotionColor: Record<string, string> = {
  happy: colors.happy,
  calm: colors.calm,
  sad: colors.sad,
  anxious: colors.anxious,
  confused: colors.confused,
  neutral: colors.neutral,
  nostalgic: '#A78BFA',
  engaged: colors.success,
};
